version: "3"

services:
  api: 
    build: "./api"
    ports:
      - "8080:8080"
    links:
      - my_db
  my_db:
    build: "./db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: terniumroot
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: